package org.feather.shardingjdbc.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.feather.shardingjdbc.model.Order;
import org.feather.shardingjdbc.model.OrderExample;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order1
     *
     * @mbg.generated Fri Aug 04 21:54:06 CST 2023
     */
    int updateByPrimaryKey(Order record);
}